name: autorop test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          3.6,   # oldest python3 that receives security updates
          '3.x'  # latest stable python3
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pytest pytest-rerunfailures coverage
        pip install -r requirements.txt
        # install this as a package, to make pytest and python imports happy
        pip install .
        git clone https://github.com/niklasb/libc-database ~/.libc-database
        ~/.libc-database/get ubuntu
    - name: Lint with black
      run: |
        black --check --diff --color .
    - name: Typecheck with mypy
      run: |
        mypy -p autorop
    - name: Test with pytest
      env:
        TERM: xterm  # ensure pwntools import works
      run: |
        coverage run -m pytest --reruns 3
    - name: Check if code coverage is sufficient
      run: |
        coverage report
